# Generated by Django 3.2 on 2022-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=255, null=True, verbose_name='Github')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialização')),
                ('history', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quem sou eu')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('url_repository', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do repositório')),
                ('url_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL da imagem')),
            ],
        ),
    ]
